export const MessageCodes = {
  // Auth
  REGISTER_SUCCESS: 'AUTH.REGISTER.SUCCESS',
  VERIFY_SUCCESS: 'AUTH.VERIFY.SUCCESS',
  LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
  LOGOUT_SUCCESS: 'AUTH.LOGOUT.SUCCESS',
  REFRESH_SUCCESS: 'AUTH.REFRESH.SUCCESS',
  PROFILE_RETRIEVED: 'AUTH.PROFILE.RETRIEVED',
  EMAIL_ALREADY_EXISTS: 'AUTH.REGISTER.EMAIL_EXISTS',
  USER_ALREADY_EXISTS: 'AUTH.REGISTER.USER_EXISTS',
  INVALID_CREDENTIALS: 'AUTH.LOGIN.INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED: 'AUTH.LOGIN.NOT_VERIFIED',
  ACCOUNT_DISABLED: 'AUTH.LOGIN.ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'AUTH.LOGIN.ACCOUNT_LOCKED',
  INVALID_OTP: 'AUTH.VERIFY.INVALID_OTP',
  OTP_EXPIRED: 'AUTH.VERIFY.OTP_EXPIRED',
  INVALID_TOKEN: 'AUTH.VERIFY.INVALID_TOKEN',
  INVALID_REFRESH_TOKEN: 'AUTH.REFRESH.INVALID_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'AUTH.REFRESH.TOKEN_EXPIRED',
  FORGOT_PASSWORD_SUCCESS: 'AUTH.FORGOT_PASSWORD.SUCCESS',
  RESET_PASSWORD_SUCCESS: 'AUTH.RESET_PASSWORD.SUCCESS',
  CHANGE_PASSWORD_SUCCESS: 'AUTH.CHANGE_PASSWORD.SUCCESS',
  SAME_PASSWORD: 'AUTH.PASSWORD.SAME_PASSWORD',
  WRONG_CURRENT_PASSWORD: 'AUTH.CHANGE_PASSWORD.WRONG_CURRENT_PASSWORD',
  OAUTH_NO_PASSWORD: 'AUTH.CHANGE_PASSWORD.OAUTH_NO_PASSWORD',
  INSUFFICIENT_PERMISSIONS: 'AUTH.INSUFFICIENT_PERMISSIONS',
  RESEND_OTP_SUCCESS: 'AUTH.RESEND_OTP.SUCCESS',
  ALREADY_VERIFIED: 'AUTH.VERIFY.ALREADY_VERIFIED',

  // Users
  USER_CREATED: 'USER.CREATE.SUCCESS',
  USER_UPDATED: 'USER.UPDATE.SUCCESS',
  USER_DELETED: 'USER.DELETE.SUCCESS',
  USER_RETRIEVED: 'USER.GET.SUCCESS',
  USER_LIST_RETRIEVED: 'USER.LIST.SUCCESS',
  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER.EMAIL.EXISTS',
  USER_PHONE_EXISTS: 'USER.PHONE.EXISTS',

  // Services
  SERVICE_CREATED: 'SERVICE.CREATE.SUCCESS',
  SERVICE_UPDATED: 'SERVICE.UPDATE.SUCCESS',
  SERVICE_DELETED: 'SERVICE.DELETE.SUCCESS',
  SERVICE_RESTORED: 'SERVICE.RESTORE.SUCCESS',
  SERVICE_RETRIEVED: 'SERVICE.GET.SUCCESS',
  SERVICE_LIST_RETRIEVED: 'SERVICE.LIST.SUCCESS',
  SERVICE_STATISTICS_RETRIEVED: 'SERVICE.STATISTICS.SUCCESS',
  SERVICE_NOT_FOUND: 'SERVICE.NOT_FOUND',
  SERVICE_NAME_EXISTS: 'SERVICE.CREATE.NAME_EXISTS',
  SERVICE_HAS_ACTIVE_BOOKINGS: 'SERVICE.DELETE.HAS_ACTIVE_BOOKINGS',

  // Upload
  FILE_UPLOADED: 'UPLOAD.SUCCESS',
  FILE_UPLOAD_FAILED: 'UPLOAD.FAILED',
  FILE_INVALID_TYPE: 'UPLOAD.INVALID_TYPE',
  FILE_TOO_LARGE: 'UPLOAD.FILE_TOO_LARGE',

  // Medications
  MEDICATION_CREATED: 'MEDICATION.CREATE.SUCCESS',
  MEDICATION_UPDATED: 'MEDICATION.UPDATE.SUCCESS',
  MEDICATION_DELETED: 'MEDICATION.DELETE.SUCCESS',
  MEDICATION_RETRIEVED: 'MEDICATION.GET.SUCCESS',
  MEDICATION_LIST_RETRIEVED: 'MEDICATION.LIST.SUCCESS',
  MEDICATION_SEARCH_SUCCESS: 'MEDICATION.SEARCH.SUCCESS',
  MEDICATION_NOT_FOUND: 'MEDICATION.NOT_FOUND',

  // Notification Time Slots
  NOTIFICATION_TIME_SLOT_CREATED: 'NOTIFICATION_TIME_SLOT.CREATE.SUCCESS',
  NOTIFICATION_TIME_SLOT_UPDATED: 'NOTIFICATION_TIME_SLOT.UPDATE.SUCCESS',
  NOTIFICATION_TIME_SLOT_DELETED: 'NOTIFICATION_TIME_SLOT.DELETE.SUCCESS',
  NOTIFICATION_TIME_SLOT_RETRIEVED: 'NOTIFICATION_TIME_SLOT.GET.SUCCESS',
  NOTIFICATION_TIME_SLOT_LIST_RETRIEVED: 'NOTIFICATION_TIME_SLOT.LIST.SUCCESS',
  NOTIFICATION_TIME_SLOT_NOT_FOUND: 'NOTIFICATION_TIME_SLOT.NOT_FOUND',

  // User Relationships
  RELATIONSHIP_INVITED: 'RELATIONSHIP.INVITED.SUCCESS',
  RELATIONSHIP_ACCEPTED: 'RELATIONSHIP.ACCEPTED.SUCCESS',
  RELATIONSHIP_REVOKED: 'RELATIONSHIP.REVOKED.SUCCESS',
  RELATIONSHIP_DELETED: 'RELATIONSHIP.DELETED.SUCCESS',
  RELATIONSHIP_RETRIEVED: 'RELATIONSHIP.GET.SUCCESS',
  RELATIONSHIP_LIST_RETRIEVED: 'RELATIONSHIP.LIST.SUCCESS',
  RELATIONSHIP_NOT_FOUND: 'RELATIONSHIP.NOT_FOUND',
  RELATIONSHIP_ALREADY_EXISTS: 'RELATIONSHIP.ALREADY_EXISTS',
  RELATIONSHIP_NOT_PENDING: 'RELATIONSHIP.NOT_PENDING',

  // Medication Conditions
  MEDICATION_CONDITION_CREATED: 'MEDICATION_CONDITION.CREATE.SUCCESS',
  MEDICATION_CONDITION_UPDATED: 'MEDICATION_CONDITION.UPDATE.SUCCESS',
  MEDICATION_CONDITION_DELETED: 'MEDICATION_CONDITION.DELETE.SUCCESS',
  MEDICATION_CONDITION_RETRIEVED: 'MEDICATION_CONDITION.GET.SUCCESS',
  MEDICATION_CONDITION_LIST_RETRIEVED: 'MEDICATION_CONDITION.LIST.SUCCESS',
  MEDICATION_CONDITION_NOT_FOUND: 'MEDICATION_CONDITION.NOT_FOUND',
  MEDICATION_CONDITION_SLUG_EXISTS: 'MEDICATION_CONDITION.CREATE.SLUG_EXISTS',

  // Reminder Schedules
  REMINDER_SCHEDULE_CREATED: 'REMINDER_SCHEDULE.CREATE.SUCCESS',
  REMINDER_SCHEDULE_UPDATED: 'REMINDER_SCHEDULE.UPDATE.SUCCESS',
  REMINDER_SCHEDULE_DELETED: 'REMINDER_SCHEDULE.DELETE.SUCCESS',
  REMINDER_SCHEDULE_RETRIEVED: 'REMINDER_SCHEDULE.GET.SUCCESS',
  REMINDER_SCHEDULE_LIST_RETRIEVED: 'REMINDER_SCHEDULE.LIST.SUCCESS',
  REMINDER_SCHEDULE_NOT_FOUND: 'REMINDER_SCHEDULE.NOT_FOUND',

  // Medication Logs
  MEDICATION_LOG_CREATED: 'MEDICATION_LOG.CREATE.SUCCESS',
  MEDICATION_LOG_UPDATED: 'MEDICATION_LOG.UPDATE.SUCCESS',
  MEDICATION_LOG_DELETED: 'MEDICATION_LOG.DELETE.SUCCESS',
  MEDICATION_LOG_RETRIEVED: 'MEDICATION_LOG.GET.SUCCESS',
  MEDICATION_LOG_LIST_RETRIEVED: 'MEDICATION_LOG.LIST.SUCCESS',
  MEDICATION_LOG_NOT_FOUND: 'MEDICATION_LOG.NOT_FOUND',

  // Prescriptions
  PRESCRIPTION_CREATED: 'PRESCRIPTION.CREATE.SUCCESS',
  PRESCRIPTION_UPDATED: 'PRESCRIPTION.UPDATE.SUCCESS',
  PRESCRIPTION_DELETED: 'PRESCRIPTION.DELETE.SUCCESS',
  PRESCRIPTION_RETRIEVED: 'PRESCRIPTION.GET.SUCCESS',
  PRESCRIPTION_LIST_RETRIEVED: 'PRESCRIPTION.LIST.SUCCESS',
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION.NOT_FOUND',
  PRESCRIPTION_INVALID_DATE_RANGE: 'PRESCRIPTION.INVALID_DATE_RANGE',

  // Statistics
  STATISTICS_RETRIEVED: 'STATISTICS.GET.SUCCESS',
} as const;
