export const MessageCodes = {
  // Auth
  REGISTER_SUCCESS: 'AUTH.REGISTER.SUCCESS',
  VERIFY_SUCCESS: 'AUTH.VERIFY.SUCCESS',
  LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
  LOGOUT_SUCCESS: 'AUTH.LOGOUT.SUCCESS',
  REFRESH_SUCCESS: 'AUTH.REFRESH.SUCCESS',
  PROFILE_RETRIEVED: 'AUTH.PROFILE.RETRIEVED',
  EMAIL_ALREADY_EXISTS: 'AUTH.REGISTER.EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'AUTH.LOGIN.INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED: 'AUTH.LOGIN.NOT_VERIFIED',
  ACCOUNT_DISABLED: 'AUTH.LOGIN.ACCOUNT_DISABLED',
  INVALID_OTP: 'AUTH.VERIFY.INVALID_OTP',
  OTP_EXPIRED: 'AUTH.VERIFY.OTP_EXPIRED',
  INVALID_REFRESH_TOKEN: 'AUTH.REFRESH.INVALID_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'AUTH.REFRESH.TOKEN_EXPIRED',
  FORGOT_PASSWORD_SUCCESS: 'AUTH.FORGOT_PASSWORD.SUCCESS',
  RESET_PASSWORD_SUCCESS: 'AUTH.RESET_PASSWORD.SUCCESS',

  // Users
  USER_CREATED: 'USER.CREATE.SUCCESS',
  USER_UPDATED: 'USER.UPDATE.SUCCESS',
  USER_DELETED: 'USER.DELETE.SUCCESS',
  USER_RETRIEVED: 'USER.GET.SUCCESS',
  USER_LIST_RETRIEVED: 'USER.LIST.SUCCESS',
  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER.EMAIL.EXISTS',
  USER_PHONE_EXISTS: 'USER.PHONE.EXISTS',

  // Services
  SERVICE_CREATED: 'SERVICE.CREATE.SUCCESS',
  SERVICE_UPDATED: 'SERVICE.UPDATE.SUCCESS',
  SERVICE_DELETED: 'SERVICE.DELETE.SUCCESS',
  SERVICE_RESTORED: 'SERVICE.RESTORE.SUCCESS',
  SERVICE_RETRIEVED: 'SERVICE.GET.SUCCESS',
  SERVICE_LIST_RETRIEVED: 'SERVICE.LIST.SUCCESS',
  SERVICE_STATISTICS_RETRIEVED: 'SERVICE.STATISTICS.SUCCESS',
  SERVICE_NOT_FOUND: 'SERVICE.NOT_FOUND',
  SERVICE_NAME_EXISTS: 'SERVICE.CREATE.NAME_EXISTS',
  SERVICE_HAS_ACTIVE_BOOKINGS: 'SERVICE.DELETE.HAS_ACTIVE_BOOKINGS',

  // Bookings
  BOOKING_CREATED: 'BOOKING.CREATE.SUCCESS',
  BOOKING_UPDATED: 'BOOKING.UPDATE.SUCCESS',
  BOOKING_CANCELLED: 'BOOKING.CANCEL.SUCCESS',
  BOOKING_DELETED: 'BOOKING.DELETE.SUCCESS',
  BOOKING_RETRIEVED: 'BOOKING.GET.SUCCESS',
  BOOKING_LIST_RETRIEVED: 'BOOKING.LIST.SUCCESS',
  BOOKING_NOT_FOUND: 'BOOKING.NOT_FOUND',
  BOOKING_DUPLICATE: 'BOOKING.CREATE.DUPLICATE',
  BOOKING_INVALID_DATE: 'BOOKING.CREATE.INVALID_DATE',
  BOOKING_INVALID_STATUS_TRANSITION: 'BOOKING.UPDATE.INVALID_TRANSITION',

  // Queue
  QUEUE_PROMOTED: 'QUEUE.PROMOTE.SUCCESS',
  QUEUE_RETRIEVED: 'QUEUE.GET.SUCCESS',
  QUEUE_LIST_RETRIEVED: 'QUEUE.LIST.SUCCESS',
  QUEUE_STATISTICS_RETRIEVED: 'QUEUE.STATISTICS.SUCCESS',
  QUEUE_NOT_FOUND: 'QUEUE.NOT_FOUND',
  QUEUE_SLOT_FULL: 'QUEUE.PROMOTE.SLOT_FULL',

  // Suggestions
  SUGGESTIONS_RETRIEVED: 'SUGGESTIONS.GET.SUCCESS',

  // Schedules
  SCHEDULE_CREATED: 'SCHEDULE.CREATE.SUCCESS',
  SCHEDULE_UPDATED: 'SCHEDULE.UPDATE.SUCCESS',
  SCHEDULE_DELETED: 'SCHEDULE.DELETE.SUCCESS',
  SCHEDULE_RETRIEVED: 'SCHEDULE.GET.SUCCESS',
  SCHEDULE_LIST_RETRIEVED: 'SCHEDULE.LIST.SUCCESS',
  SCHEDULE_NOT_FOUND: 'SCHEDULE.NOT_FOUND',
  SCHEDULE_CONFLICT: 'SCHEDULE.CREATE.CONFLICT',
  AVAILABLE_SLOTS_RETRIEVED: 'SCHEDULE.SLOTS.SUCCESS',

  // Venue
  VENUE_CREATED: 'VENUE.CREATE.SUCCESS',
  VENUE_UPDATED: 'VENUE.UPDATE.SUCCESS',
  VENUE_DELETED: 'VENUE.DELETE.SUCCESS',
  VENUE_RETRIEVED: 'VENUE.GET.SUCCESS',
  VENUE_LIST_RETRIEVED: 'VENUE.LIST.SUCCESS',
  VENUE_APP_ORDERABLE_RETRIEVED: 'VENUE.APP_ORDERABLE.SUCCESS',
  VENUE_NOT_FOUND: 'VENUE.NOT_FOUND',

  // Menu - Categories
  CATEGORY_CREATED: 'CATEGORY.CREATE.SUCCESS',
  CATEGORY_UPDATED: 'CATEGORY.UPDATE.SUCCESS',
  CATEGORY_DELETED: 'CATEGORY.DELETE.SUCCESS',
  CATEGORY_RETRIEVED: 'CATEGORY.GET.SUCCESS',
  CATEGORY_LIST_RETRIEVED: 'CATEGORY.LIST.SUCCESS',
  CATEGORY_NOT_FOUND: 'CATEGORY.NOT_FOUND',
  CATEGORY_HAS_DISHES: 'CATEGORY.DELETE.HAS_DISHES',

  // Menu - Dishes
  DISH_CREATED: 'DISH.CREATE.SUCCESS',
  DISH_UPDATED: 'DISH.UPDATE.SUCCESS',
  DISH_DELETED: 'DISH.DELETE.SUCCESS',
  DISH_RETRIEVED: 'DISH.GET.SUCCESS',
  DISH_LIST_RETRIEVED: 'DISH.LIST.SUCCESS',
  DISH_NOT_FOUND: 'DISH.NOT_FOUND',
  DISH_AVAILABILITY_TOGGLED: 'DISH.TOGGLE.SUCCESS',
  DISH_NOT_AVAILABLE: 'DISH.NOT_AVAILABLE',

  // Service Area
  SERVICE_AREA_CREATED: 'SERVICE_AREA.CREATE.SUCCESS',
  SERVICE_AREA_UPDATED: 'SERVICE_AREA.UPDATE.SUCCESS',
  SERVICE_AREA_DELETED: 'SERVICE_AREA.DELETE.SUCCESS',
  SERVICE_AREA_RETRIEVED: 'SERVICE_AREA.GET.SUCCESS',
  SERVICE_AREA_LIST_RETRIEVED: 'SERVICE_AREA.LIST.SUCCESS',
  SERVICE_AREA_TABLES_RETRIEVED: 'SERVICE_AREA.TABLES.SUCCESS',
  SERVICE_AREA_ROOMS_RETRIEVED: 'SERVICE_AREA.ROOMS.SUCCESS',
  SERVICE_AREA_NOT_FOUND: 'SERVICE_AREA.NOT_FOUND',
  SERVICE_AREA_HAS_ORDERS: 'SERVICE_AREA.DELETE.HAS_ORDERS',

  // QR Code
  QR_CODE_GENERATED: 'QR_CODE.GENERATE.SUCCESS',
  QR_CODE_VALIDATED: 'QR_CODE.VALIDATE.SUCCESS',
  QR_CODE_DELETED: 'QR_CODE.DELETE.SUCCESS',
  QR_CODE_RETRIEVED: 'QR_CODE.GET.SUCCESS',
  QR_CODE_LIST_RETRIEVED: 'QR_CODE.LIST.SUCCESS',
  QR_CODE_NOT_FOUND: 'QR_CODE.NOT_FOUND',
  QR_CODE_INACTIVE: 'QR_CODE.INACTIVE',
  QR_CODE_TOGGLED: 'QR_CODE.TOGGLE.SUCCESS',

  // Order
  ORDER_CREATED: 'ORDER.CREATE.SUCCESS',
  ORDER_CONFIRMED: 'ORDER.CONFIRM.SUCCESS',
  ORDER_REJECTED: 'ORDER.REJECT.SUCCESS',
  ORDER_UPDATED: 'ORDER.UPDATE.SUCCESS',
  ORDER_CANCELLED: 'ORDER.CANCEL.SUCCESS',
  ORDER_RETRIEVED: 'ORDER.GET.SUCCESS',
  ORDER_LIST_RETRIEVED: 'ORDER.LIST.SUCCESS',
  ORDER_PENDING_RETRIEVED: 'ORDER.PENDING.SUCCESS',
  ORDER_NOT_FOUND: 'ORDER.NOT_FOUND',
  ORDER_INVALID_STATUS: 'ORDER.INVALID_STATUS',
  ORDER_CANNOT_CANCEL: 'ORDER.CANCEL.INVALID_STATUS',
  ORDER_ITEM_UPDATED: 'ORDER.ITEM.UPDATE.SUCCESS',
  ORDER_ITEMS_RETRIEVED: 'ORDER.ITEMS.SUCCESS',
  ORDER_ITEM_NOT_FOUND: 'ORDER.ITEM.NOT_FOUND',

  // Upload
  FILE_UPLOADED: 'UPLOAD.SUCCESS',
  FILE_UPLOAD_FAILED: 'UPLOAD.FAILED',
  FILE_INVALID_TYPE: 'UPLOAD.INVALID_TYPE',
  FILE_TOO_LARGE: 'UPLOAD.FILE_TOO_LARGE',

  // Reports
  REPORT_GENERATED: 'REPORT.GENERATE.SUCCESS',
  REPORT_RETRIEVED: 'REPORT.GET.SUCCESS',
  REPORT_NOT_FOUND: 'REPORT.NOT_FOUND',
} as const;
